import { ConfigPack } from './ConfigSchema';

/**
 * 内置配置包（提审 / 离线必带）。
 * 等价于 design 里的 default.pack.json：Cocos 脚本侧用 TS 常量，避免再挂一套 resources 加载。
 * 远程包以后走同一 Schema，由 ConfigStore.tryApply 校验。
 */
export const BUILTIN_PACK: ConfigPack = {
    version: 37,
    publishedAt: '2026-09-25',
    characters: [
        {
            id: 'knight',
            name: '骑士',
            emoji: '🛡️',
            desc: '均衡。生命与防御更高。',
            cost: 0,
            skinId: 'knight',
            exclusiveWeaponId: 'sword',
            base: { maxHp: 120, atk: 22, def: 2, moveSpeed: 158, critChance: 0.15, critMultiplier: 1.5 },
        },
        {
            id: 'ranger',
            name: '游侠',
            emoji: '🏹',
            desc: '更快，暴击更高，生命更少。',
            cost: 12,
            skinId: 'ranger',
            exclusiveWeaponId: 'bow',
            base: { maxHp: 90, atk: 24, def: 0, moveSpeed: 198, critChance: 0.22, critMultiplier: 1.5 },
        },
        {
            id: 'mage',
            name: '法师',
            emoji: '🔮',
            desc: '攻击更高，移动更慢。',
            cost: 18,
            skinId: 'mage',
            exclusiveWeaponId: 'wand',
            base: { maxHp: 85, atk: 34, def: 0, moveSpeed: 135, critChance: 0.15, critMultiplier: 1.7 },
        },
        {
            id: 'paladin',
            name: '圣骑士',
            emoji: '⚜️',
            desc: '圣光壁垒。极高生命与防御；开局圣光巨刃，局内另寻掉落。',
            cost: 48,
            skinId: 'paladin',
            exclusiveWeaponId: 'holy_blade',
            base: { maxHp: 150, atk: 24, def: 5, moveSpeed: 135, critChance: 0.12, critMultiplier: 1.55 },
        },
        {
            id: 'assassin',
            name: '影刃',
            emoji: '🗡️',
            desc: '暗影闪击。高速高暴击；开局影舞双匕。',
            cost: 55,
            skinId: 'assassin',
            exclusiveWeaponId: 'shadow_daggers',
            base: { maxHp: 75, atk: 26, def: 0, moveSpeed: 205, critChance: 0.32, critMultiplier: 2.0 },
        },
        {
            id: 'dragonkin',
            name: '龙裔',
            emoji: '🐉',
            desc: '龙血沸腾。重击与火焰吐息；开局龙牙戟。',
            cost: 68,
            skinId: 'dragonkin',
            exclusiveWeaponId: 'dragon_fang',
            base: { maxHp: 100, atk: 36, def: 2, moveSpeed: 140, critChance: 0.18, critMultiplier: 1.8 },
        },
        {
            id: 'berserker',
            name: '狂战',
            emoji: '🪓',
            desc: '浴血近战。高攻低防；开局血劈巨斧。',
            cost: 52,
            skinId: 'berserker',
            exclusiveWeaponId: 'blood_cleaver',
            base: { maxHp: 90, atk: 34, def: 0, moveSpeed: 165, critChance: 0.2, critMultiplier: 1.85 },
        },
        {
            id: 'geomancer',
            name: '地脉师',
            emoji: '🪨',
            desc: '岩盾法师。偏坦；开局岩晶杖，局内另寻掉落。',
            cost: 58,
            skinId: 'geomancer',
            exclusiveWeaponId: 'earth_staff',
            base: { maxHp: 120, atk: 26, def: 4, moveSpeed: 130, critChance: 0.12, critMultiplier: 1.55 },
        },
        {
            id: 'stormcaller',
            name: '唤雷',
            emoji: '⚡',
            desc: '疾风雷击。高速中距；开局唤雷杖。',
            cost: 62,
            skinId: 'stormcaller',
            exclusiveWeaponId: 'storm_rod',
            base: { maxHp: 85, atk: 28, def: 1, moveSpeed: 175, critChance: 0.2, critMultiplier: 1.7 },
        },
        {
            id: 'cryomancer',
            name: '霜语',
            emoji: '❄️',
            desc: '寒霜法师。偏坦控场；开局冰晶球。',
            cost: 60,
            skinId: 'cryomancer',
            exclusiveWeaponId: 'glacier_orb',
            base: { maxHp: 115, atk: 27, def: 3, moveSpeed: 128, critChance: 0.14, critMultiplier: 1.55 },
        },
        {
            id: 'warden',
            name: '戟卫',
            emoji: '🔱',
            desc: '中距戟术。均衡攻防；开局守望戟。',
            cost: 54,
            skinId: 'warden',
            exclusiveWeaponId: 'ward_glaive',
            base: { maxHp: 125, atk: 25, def: 3, moveSpeed: 150, critChance: 0.16, critMultiplier: 1.6 },
        },
        {
            id: 'plague',
            name: '疫医',
            emoji: '🧪',
            desc: '毒雾疾射。高机动力；开局毒瓶。',
            cost: 56,
            skinId: 'plague',
            exclusiveWeaponId: 'venom_vials',
            base: { maxHp: 88, atk: 24, def: 1, moveSpeed: 170, critChance: 0.22, critMultiplier: 1.65 },
        },
        {
            id: 'voidwalker',
            name: '虚空行者',
            emoji: '🌑',
            desc: '裂隙刺客。极高暴击与移速；开局虚空刃。',
            cost: 72,
            skinId: 'voidwalker',
            exclusiveWeaponId: 'void_edge',
            base: { maxHp: 82, atk: 30, def: 1, moveSpeed: 195, critChance: 0.28, critMultiplier: 2.1 },
        },
        {
            id: 'sunpriest',
            name: '日曜祭司',
            emoji: '☀️',
            desc: '圣焰法坦。厚血；开局日轮杖。',
            cost: 70,
            skinId: 'sunpriest',
            exclusiveWeaponId: 'solar_scepter',
            base: { maxHp: 130, atk: 29, def: 3, moveSpeed: 132, critChance: 0.15, critMultiplier: 1.65 },
        },
    ],
    weapons: [
        {
            id: 'sword', name: '铁剑', emoji: '🗡️', type: 'melee',
            damage: 24, cooldown: 0.42, range: 118, coneHalf: 78, multiHit: 1,
            fireMode: 'slash', knockback: 14,
            rarity: 'white', unlockFloor: 1, dropWeight: 0,
            description: '【挥砍】标准直剑。扇形快斩，节奏稳。',
        },
        {
            id: 'dagger', name: '双刃匕首', emoji: '⚔️', type: 'melee',
            damage: 12, cooldown: 0.16, range: 90, coneHalf: 60, multiHit: 2,
            fireMode: 'flurry',
            rarity: 'white', unlockFloor: 1, dropWeight: 12,
            description: '【连击】交叉双匕。两段快刺，贴脸爆发。',
        },
        {
            id: 'bow', name: '木弓', emoji: '🏹', type: 'ranged',
            damage: 20, cooldown: 0.5, range: 650, coneHalf: 0, multiHit: 1,
            bulletSpeed: 600, bulletSize: 12, bulletColor: [255, 220, 60, 255], bulletShape: 'arrow',
            fireMode: 'bolt', knockback: 10,
            rarity: 'green', unlockFloor: 1, dropWeight: 0,
            description: '【单发】高速直箭。中远程点名。',
        },
        {
            id: 'wand', name: '魔法杖', emoji: '🪄', type: 'ranged',
            damage: 35, cooldown: 1.2, range: 420, coneHalf: 0, multiHit: 1,
            bulletSpeed: 280, bulletSize: 18, bulletColor: [180, 80, 255, 255], bulletShape: 'orb',
            fireMode: 'bolt',
            piercing: true,
            rarity: 'purple', unlockFloor: 1, dropWeight: 0,
            description: '【穿透弹】三棱奥术晶。慢速高伤，穿透整排。',
        },
        {
            id: 'spear', name: '长矛', emoji: '🔱', type: 'melee',
            damage: 16, cooldown: 0.52, range: 170, coneHalf: 22, multiHit: 1,
            fireMode: 'thrust', knockback: 30,
            rarity: 'green', unlockFloor: 1, dropWeight: 10,
            description: '【突刺穿排】细长矛。窄线贯穿，顶飞前排。',
        },
        {
            id: 'axe', name: '巨斧', emoji: '🪓', type: 'melee',
            damage: 34, cooldown: 0.95, range: 100, coneHalf: 100, multiHit: 1,
            fireMode: 'heavy', knockback: 46,
            rarity: 'blue', unlockFloor: 2, dropWeight: 7,
            description: '【重击】单侧大斧。超宽挥砍，清近身一团。',
        },
        {
            id: 'hammer', name: '战锤', emoji: '🔨', type: 'melee',
            damage: 42, cooldown: 1.15, range: 90, coneHalf: 48, multiHit: 1,
            fireMode: 'heavy', knockback: 40, splash: 84,
            rarity: 'blue', unlockFloor: 2, dropWeight: 5,
            description: '【重击·震地】方锤砸落。落点环形震波。',
        },
        {
            id: 'crossbow', name: '重弩', emoji: '🎯', type: 'ranged',
            damage: 28, cooldown: 0.9, range: 720, coneHalf: 0, multiHit: 1,
            bulletSpeed: 760, bulletSize: 10, bulletColor: [220, 230, 255, 255], bulletShape: 'arrow',
            fireMode: 'bolt', knockback: 34,
            piercing: true,
            rarity: 'blue', unlockFloor: 2, dropWeight: 5,
            description: '【穿透弩矢】极速重矢。装填慢，穿甲推人。',
        },
        {
            id: 'shuriken', name: '手里剑', emoji: '✴️', type: 'ranged',
            damage: 8, cooldown: 0.2, range: 460, coneHalf: 0, multiHit: 1,
            bulletSpeed: 640, bulletSize: 8, bulletColor: [200, 210, 230, 255], bulletShape: 'ball',
            fireMode: 'bounce', bounce: 3,
            rarity: 'green', unlockFloor: 1, dropWeight: 9,
            description: '【弹墙】四尖星镖。连发弹壁，窄廊切怪。',
        },
        {
            id: 'frost', name: '冰杖', emoji: '❄️', type: 'ranged',
            damage: 14, cooldown: 0.55, range: 480, coneHalf: 0, multiHit: 1,
            bulletSpeed: 400, bulletSize: 12, bulletColor: [140, 220, 255, 255], bulletShape: 'orb',
            fireMode: 'burst', burst: 3, slow: [0.45, 1.6],
            rarity: 'purple', unlockFloor: 3, dropWeight: 3,
            description: '【冰晶点射】三连冰棱。强减速，控场优先。',
        },
        {
            id: 'holy_blade', name: '圣光巨刃', emoji: '⚔️', type: 'melee',
            damage: 38, cooldown: 0.7, range: 130, coneHalf: 75, multiHit: 1,
            fireMode: 'wave', knockback: 18,
            rarity: 'gold', unlockFloor: 1, dropWeight: 0,
            description: '【圣光剑气】宽刃斩出穿透光波。圣骑士开局。',
        },
        {
            id: 'shadow_daggers', name: '影舞双匕', emoji: '🔪', type: 'melee',
            damage: 14, cooldown: 0.14, range: 90, coneHalf: 50, multiHit: 3,
            fireMode: 'flurry',
            rarity: 'gold', unlockFloor: 1, dropWeight: 0,
            description: '【影刺三连】弯刃极速三连。影刃开局。',
        },
        {
            id: 'dragon_fang', name: '龙牙戟', emoji: '🔥', type: 'ranged',
            damage: 30, cooldown: 0.65, range: 520, coneHalf: 0, multiHit: 1,
            bulletSpeed: 420, bulletSize: 16, bulletColor: [255, 120, 40, 255], bulletShape: 'orb',
            fireMode: 'lob', splash: 72,
            rarity: 'gold', unlockFloor: 1, dropWeight: 0,
            description: '【龙火投掷】弯月牙喷火球，落地灼圈。龙裔开局。',
        },
        {
            id: 'blood_cleaver', name: '血劈巨斧', emoji: '🩸', type: 'melee',
            damage: 40, cooldown: 0.85, range: 118, coneHalf: 98, multiHit: 2,
            fireMode: 'heavy', knockback: 42, splash: 56,
            rarity: 'gold', unlockFloor: 1, dropWeight: 0,
            description: '【双刃血劈】双斧刃重挥 + 血雾溅射。狂战开局。',
        },
        {
            id: 'earth_staff', name: '岩晶杖', emoji: '🟤', type: 'ranged',
            damage: 32, cooldown: 1.05, range: 380, coneHalf: 0, multiHit: 1,
            bulletSpeed: 220, bulletSize: 22, bulletColor: [180, 140, 80, 255], bulletShape: 'orb',
            fireMode: 'lob', splash: 90, knockback: 36,
            rarity: 'gold', unlockFloor: 1, dropWeight: 0,
            description: '【岩爆抛投】晶簇砸地，大范围震退。地脉师开局。',
        },
        {
            id: 'storm_rod', name: '唤雷杖', emoji: '⚡', type: 'ranged',
            damage: 24, cooldown: 0.38, range: 560, coneHalf: 0, multiHit: 1,
            bulletSpeed: 540, bulletSize: 12, bulletColor: [120, 220, 255, 255], bulletShape: 'ball',
            fireMode: 'beam',
            rarity: 'gold', unlockFloor: 1, dropWeight: 0,
            description: '【电弧射线】瞬时锯齿电弧到墙。唤雷开局。',
        },
        {
            id: 'sunblade', name: '曜金长剑', emoji: '☀️', type: 'melee',
            damage: 26, cooldown: 0.5, range: 120, coneHalf: 72, multiHit: 1,
            fireMode: 'wave', knockback: 14,
            rarity: 'purple', unlockFloor: 3, dropWeight: 4,
            description: '【日轮剑气】细金刃甩出短距光波，节奏比圣刃更快。',
        },
        {
            id: 'venom_bow', name: '毒藤弓', emoji: '🌿', type: 'ranged',
            damage: 16, cooldown: 0.48, range: 620, coneHalf: 0, multiHit: 1,
            bulletSpeed: 520, bulletSize: 11, bulletColor: [120, 220, 90, 255], bulletShape: 'arrow',
            fireMode: 'burst', burst: 3, slow: [0.75, 1.0],
            rarity: 'blue', unlockFloor: 2, dropWeight: 6,
            description: '【淬毒点射】三连毒箭，命中拖慢。风筝专用。',
        },
        {
            id: 'glacier_orb', name: '冰晶球', emoji: '🧊', type: 'ranged',
            damage: 27, cooldown: 0.95, range: 400, coneHalf: 0, multiHit: 1,
            bulletSpeed: 260, bulletSize: 20, bulletColor: [140, 220, 255, 255], bulletShape: 'orb',
            fireMode: 'lob', splash: 88, slow: [0.4, 1.8],
            rarity: 'gold', unlockFloor: 1, dropWeight: 0,
            description: '【冰爆抛投】悬浮冰球砸地碎裂冻圈。霜语开局。',
        },
        {
            id: 'ward_glaive', name: '守望戟', emoji: '🔱', type: 'melee',
            damage: 30, cooldown: 0.55, range: 155, coneHalf: 34, multiHit: 1,
            fireMode: 'thrust', knockback: 36,
            rarity: 'gold', unlockFloor: 1, dropWeight: 0,
            description: '【戟突·护徽】月牙戟突刺，扇角比长矛更宽。戟卫开局。',
        },
        {
            id: 'venom_vials', name: '毒瓶', emoji: '🧴', type: 'ranged',
            damage: 14, cooldown: 0.28, range: 480, coneHalf: 0, multiHit: 1,
            bulletSpeed: 460, bulletSize: 10, bulletColor: [100, 220, 80, 255], bulletShape: 'ball',
            fireMode: 'lob', splash: 60, slow: [0.65, 1.2],
            rarity: 'gold', unlockFloor: 1, dropWeight: 0,
            description: '【连投毒瓶】双瓶高速抛物溅毒。疫医开局。',
        },
        {
            id: 'void_edge', name: '虚空刃', emoji: '🌑', type: 'melee',
            damage: 24, cooldown: 0.22, range: 110, coneHalf: 55, multiHit: 1,
            fireMode: 'wave', knockback: 10,
            rarity: 'gold', unlockFloor: 1, dropWeight: 0,
            description: '【裂隙剑气】弯刃甩出短距虚空波。虚空行者开局。',
        },
        {
            id: 'solar_scepter', name: '日轮杖', emoji: '🌞', type: 'ranged',
            damage: 32, cooldown: 0.85, range: 480, coneHalf: 0, multiHit: 1,
            bulletSpeed: 320, bulletSize: 18, bulletColor: [255, 200, 80, 255], bulletShape: 'orb',
            fireMode: 'homing',
            piercing: true,
            rarity: 'gold', unlockFloor: 1, dropWeight: 0,
            description: '【追踪日轮】日环弹拐弯追敌并穿透。日曜祭司开局。',
        },
        {
            id: 'starfall_bow', name: '星陨弓', emoji: '🌠', type: 'ranged',
            damage: 22, cooldown: 0.62, range: 700, coneHalf: 0, multiHit: 1,
            bulletSpeed: 620, bulletSize: 12, bulletColor: [255, 230, 140, 255], bulletShape: 'arrow',
            fireMode: 'spread', pellets: 3, spreadDeg: 16,
            rarity: 'gold', unlockFloor: 4, dropWeight: 2,
            description: '【三星霰射】一弓三星扇形齐发。近全中、远点名。',
        },
        {
            id: 'scatter_gun', name: '碎石铳', emoji: '💥', type: 'ranged',
            damage: 30, cooldown: 0.8, range: 340, coneHalf: 0, multiHit: 1,
            bulletSpeed: 700, bulletSize: 7, bulletColor: [230, 200, 140, 255], bulletShape: 'ball',
            fireMode: 'spread', pellets: 5, spreadDeg: 34, knockback: 18,
            rarity: 'blue', unlockFloor: 2, dropWeight: 6,
            description: '【五粒霰射】短管喷碎石，贴脸爆炸伤，远了散开。',
        },
        {
            id: 'saw_disc', name: '回旋锯', emoji: '🪚', type: 'ranged',
            damage: 18, cooldown: 0.55, range: 900, coneHalf: 0, multiHit: 1,
            bulletSpeed: 520, bulletSize: 14, bulletColor: [200, 210, 220, 255], bulletShape: 'ball',
            fireMode: 'bounce', bounce: 4,
            rarity: 'purple', unlockFloor: 3, dropWeight: 4,
            description: '【弹墙锯片】齿轮锯弹墙四次，走廊绞肉机。',
        },
        {
            id: 'thunder_lance', name: '雷枪', emoji: '🌩️', type: 'melee',
            damage: 34, cooldown: 0.6, range: 190, coneHalf: 20, multiHit: 1,
            fireMode: 'thrust', knockback: 44,
            rarity: 'gold', unlockFloor: 3, dropWeight: 2,
            description: '【雷突贯穿】极长电矛直线穿排，强击退。窄廊之王。',
        },
        {
            id: 'chain_whip', name: '锁链鞭', emoji: '⛓️', type: 'melee',
            damage: 18, cooldown: 0.28, range: 155, coneHalf: 70, multiHit: 3,
            fireMode: 'flurry', knockback: 10,
            rarity: 'blue', unlockFloor: 2, dropWeight: 5,
            description: '【锁链连笞】三节快抽，中距抽打。',
        },
        {
            id: 'boomerang', name: '回旋镖', emoji: '🪃', type: 'ranged',
            damage: 17, cooldown: 0.5, range: 520, coneHalf: 0, multiHit: 1,
            bulletSpeed: 480, bulletSize: 14, bulletColor: [210, 140, 70, 255], bulletShape: 'ball',
            fireMode: 'bounce', bounce: 3, knockback: 12,
            rarity: 'green', unlockFloor: 1, dropWeight: 6,
            description: '【弹墙回旋】木镖弹墙三次，窄廊连环。',
        },
        {
            id: 'flame_flask', name: '燃焰瓶', emoji: '🧴', type: 'ranged',
            damage: 28, cooldown: 0.75, range: 300, coneHalf: 0, multiHit: 1,
            bulletSpeed: 320, bulletSize: 16, bulletColor: [255, 120, 40, 255], bulletShape: 'orb',
            fireMode: 'lob', splash: 80, knockback: 20,
            rarity: 'blue', unlockFloor: 2, dropWeight: 4,
            description: '【燃焰溅射】投瓶落地爆开灼热圈。',
        },
        {
            id: 'claymore', name: '大剑', emoji: '⚔️', type: 'melee',
            damage: 42, cooldown: 0.78, range: 145, coneHalf: 85, multiHit: 1,
            fireMode: 'heavy', knockback: 48, splash: 60,
            rarity: 'purple', unlockFloor: 3, dropWeight: 3,
            description: '【重斩震荡】大开大合，落点震退。',
        },
        {
            id: 'rail_cannon', name: '磁轨炮', emoji: '📡', type: 'ranged',
            damage: 52, cooldown: 1.05, range: 560, coneHalf: 0, multiHit: 1,
            bulletSpeed: 900, bulletSize: 10, bulletColor: [120, 220, 255, 255], bulletShape: 'ball',
            fireMode: 'beam', knockback: 28,
            rarity: 'gold', unlockFloor: 4, dropWeight: 2,
            description: '【磁轨射线】瞬时直线打穿整列。',
        },
        {
            id: 'prism_rod', name: '棱镜杖', emoji: '💠', type: 'ranged',
            damage: 21, cooldown: 0.45, range: 440, coneHalf: 0, multiHit: 1,
            bulletSpeed: 360, bulletSize: 13, bulletColor: [180, 120, 255, 255], bulletShape: 'orb',
            fireMode: 'homing',
            rarity: 'purple', unlockFloor: 3, dropWeight: 3,
            description: '【光棱追踪】自动拐向最近敌人。',
        },
    ],
    enemies: [
        { id: 'slime', hp: 55, damage: 14, speed: 65, speedScale: 'room', behaviorId: 'chase', bodySize: 64, attackRange: 55, defaultColor: [90, 180, 70] },
        { id: 'fast', hp: 36, damage: 11, speed: 125, speedScale: 'flat', behaviorId: 'chase', bodySize: 48, attackRange: 55, defaultColor: [60, 180, 220] },
        { id: 'tank', hp: 140, damage: 24, speed: 40, speedScale: 'room', behaviorId: 'chase', bodySize: 80, attackRange: 70, defaultColor: [180, 60, 60] },
        { id: 'archer', hp: 50, damage: 16, speed: 70, speedScale: 'room', behaviorId: 'kite', bodySize: 56, attackRange: 420, defaultColor: [160, 140, 90] },
        { id: 'wisp', hp: 34, damage: 12, speed: 95, speedScale: 'flat', behaviorId: 'fly', bodySize: 48, attackRange: 48, defaultColor: [140, 200, 255] },
        { id: 'mage', hp: 58, damage: 22, speed: 55, speedScale: 'room', behaviorId: 'cast', bodySize: 56, attackRange: 460, defaultColor: [150, 90, 210] },
        { id: 'beetle', hp: 62, damage: 15, speed: 78, speedScale: 'room', behaviorId: 'chase', bodySize: 52, attackRange: 50, defaultColor: [90, 70, 40] },
        { id: 'bat', hp: 30, damage: 11, speed: 115, speedScale: 'flat', behaviorId: 'fly', bodySize: 44, attackRange: 44, defaultColor: [70, 50, 90] },
        { id: 'toad', hp: 50, damage: 16, speed: 88, speedScale: 'flat', behaviorId: 'chase', bodySize: 56, attackRange: 52, defaultColor: [50, 140, 70] },
        { id: 'crystal', hp: 75, damage: 18, speed: 52, speedScale: 'room', behaviorId: 'chase', bodySize: 58, attackRange: 58, defaultColor: [140, 200, 240] },
        { id: 'golem', hp: 125, damage: 22, speed: 36, speedScale: 'room', behaviorId: 'chase', bodySize: 72, attackRange: 68, defaultColor: [120, 110, 130] },
        { id: 'moth', hp: 26, damage: 9, speed: 100, speedScale: 'flat', behaviorId: 'fly', bodySize: 46, attackRange: 42, defaultColor: [200, 160, 80] },
        { id: 'dragon', hp: 170, damage: 26, speed: 72, speedScale: 'flat', behaviorId: 'dragon', bodySize: 96, attackRange: 480, defaultColor: [200, 70, 40] },
        { id: 'raven', hp: 38, damage: 14, speed: 105, speedScale: 'flat', behaviorId: 'fly', bodySize: 50, attackRange: 50, defaultColor: [40, 40, 55] },
        { id: 'mosquito', hp: 24, damage: 10, speed: 130, speedScale: 'flat', behaviorId: 'fly', bodySize: 40, attackRange: 40, defaultColor: [60, 120, 50] },
        { id: 'specter', hp: 42, damage: 15, speed: 100, speedScale: 'flat', behaviorId: 'fly', bodySize: 52, attackRange: 50, defaultColor: [180, 200, 220] },
        { id: 'bone', hp: 68, damage: 20, speed: 70, speedScale: 'room', behaviorId: 'chase', bodySize: 56, attackRange: 58, defaultColor: [220, 210, 190] },
        { id: 'spider', hp: 48, damage: 15, speed: 92, speedScale: 'flat', behaviorId: 'chase', bodySize: 54, attackRange: 52, defaultColor: [70, 50, 55] },
        { id: 'snake', hp: 42, damage: 17, speed: 100, speedScale: 'flat', behaviorId: 'chase', bodySize: 50, attackRange: 48, defaultColor: [60, 130, 70] },
        { id: 'imp', hp: 46, damage: 18, speed: 88, speedScale: 'room', behaviorId: 'chase', bodySize: 48, attackRange: 52, defaultColor: [190, 60, 50] },
        { id: 'shroom', hp: 70, damage: 14, speed: 48, speedScale: 'room', behaviorId: 'chase', bodySize: 60, attackRange: 56, defaultColor: [180, 100, 90] },
        { id: 'jelly', hp: 36, damage: 13, speed: 78, speedScale: 'flat', behaviorId: 'fly', bodySize: 52, attackRange: 46, defaultColor: [120, 200, 220] },
        { id: 'cog', hp: 70, damage: 18, speed: 70, speedScale: 'room', behaviorId: 'chase', bodySize: 58, attackRange: 54, defaultColor: [180, 120, 50] },
        { id: 'spark', hp: 28, damage: 14, speed: 120, speedScale: 'flat', behaviorId: 'fly', bodySize: 42, attackRange: 44, defaultColor: [255, 220, 80] },
        { id: 'puppet', hp: 55, damage: 16, speed: 82, speedScale: 'room', behaviorId: 'chase', bodySize: 54, attackRange: 52, defaultColor: [160, 100, 70] },
        { id: 'drone', hp: 48, damage: 17, speed: 75, speedScale: 'room', behaviorId: 'kite', bodySize: 50, attackRange: 400, defaultColor: [90, 140, 170] },
        { id: 'wolf', hp: 44, damage: 16, speed: 118, speedScale: 'flat', behaviorId: 'chase', bodySize: 52, attackRange: 50, defaultColor: [110, 100, 100] },
        { id: 'crab', hp: 80, damage: 20, speed: 55, speedScale: 'room', behaviorId: 'chase', bodySize: 60, attackRange: 58, defaultColor: [200, 80, 60] },
    ],
    mapThemes: [
        {
            id: 'cave',
            name: '幽暗洞穴',
            emoji: '🪨',
            floorDark: [42, 34, 28],
            floorLight: [58, 48, 40],
            floorEdge: [28, 22, 18],
            floorShine: [255, 220, 180, 12],
            borderColor: [18, 12, 10],
            obstacleStyle: 'rock',
            obstacleCount: 48,
            cornerCount: 4,
            obstacleDark: [50, 42, 36],
            obstacleMid: [85, 72, 60],
            obstacleLight: [120, 100, 80],
            floorMin: 1,
            floorMax: 99,
            weight: 10,
            blurb: '不规则岩洞与蜿蜒隧道，钟乳石成林、地下水洼。甲虫蓄力冲锋，重甲贴地；深层惊醒火龙。',
        },
        {
            id: 'ruins',
            name: '远古遗迹',
            emoji: '🏛️',
            floorDark: [48, 46, 58],
            floorLight: [66, 64, 78],
            floorEdge: [32, 30, 40],
            floorShine: [200, 210, 255, 14],
            borderColor: [20, 18, 28],
            obstacleStyle: 'pillar',
            obstacleCount: 36,
            cornerCount: 3,
            obstacleDark: [55, 50, 70],
            obstacleMid: [95, 88, 115],
            obstacleLight: [140, 130, 165],
            floorMin: 1,
            floorMax: 99,
            weight: 10,
            blurb: '厅室加直走廊的经典地牢：石柱阵、环沟机关板、墙弩。石偶镇守，弓手法师守柱边。',
        },
        {
            id: 'swamp',
            name: '毒雾沼泽',
            emoji: '🌿',
            floorDark: [28, 48, 32],
            floorLight: [40, 68, 44],
            floorEdge: [18, 32, 22],
            floorShine: [160, 255, 140, 12],
            borderColor: [10, 20, 12],
            obstacleStyle: 'root',
            obstacleCount: 55,
            cornerCount: 5,
            obstacleDark: [35, 55, 30],
            obstacleMid: [55, 90, 50],
            obstacleLight: [90, 130, 70],
            floorMin: 1,
            floorMax: 99,
            weight: 10,
            blurb: '一整片开阔泥沼：毒沼水洼星罗棋布，树丛作掩体。毒蛙扑跳、蚊蛾成群；追你的怪踩毒也掉血。',
        },
        {
            id: 'ice',
            name: '永冻冰原',
            emoji: '🧊',
            floorDark: [48, 68, 92],
            floorLight: [72, 98, 125],
            floorEdge: [32, 48, 68],
            floorShine: [200, 240, 255, 28],
            borderColor: [20, 32, 48],
            obstacleStyle: 'crystal',
            obstacleCount: 40,
            cornerCount: 4,
            obstacleDark: [70, 120, 170],
            obstacleMid: [120, 180, 220],
            obstacleLight: [200, 240, 255],
            floorMin: 2,
            floorMax: 99,
            weight: 8,
            blurb: '开阔冰湖，冰面更滑更快；冰裂缝把场地切成迷宫。晶爬贴地，法师弓手远程点名。',
        },
        {
            id: 'sky',
            name: '浮空云海',
            emoji: '☁️',
            floorDark: [70, 90, 130],
            floorLight: [95, 120, 165],
            floorEdge: [50, 65, 100],
            floorShine: [255, 255, 255, 35],
            borderColor: [40, 50, 80],
            obstacleStyle: 'cloud',
            obstacleCount: 32,
            cornerCount: 3,
            obstacleDark: [160, 175, 200],
            obstacleMid: [210, 220, 235],
            obstacleLight: [245, 248, 255],
            floorMin: 3,
            floorMax: 99,
            weight: 7,
            blurb: '浮岛与窄桥，岛外皆虚空：地面怪过不了桥就只能等你，飞怪才是主场。火龙盘旋喷火。',
        },
        {
            id: 'volcano',
            name: '熔岩火口',
            emoji: '🌋',
            floorDark: [52, 28, 22],
            floorLight: [78, 40, 28],
            floorEdge: [32, 16, 14],
            floorShine: [255, 140, 60, 22],
            borderColor: [24, 10, 8],
            obstacleStyle: 'rock',
            obstacleCount: 44,
            cornerCount: 4,
            obstacleDark: [60, 28, 22],
            obstacleMid: [120, 55, 35],
            obstacleLight: [200, 100, 50],
            floorMin: 2,
            floorMax: 99,
            weight: 7,
            blurb: '厅室地牢被两条熔岩河纵切，只有石桥可渡。火龙、甲虫冲锋；引怪进熔岩是本作打法。',
        },
        {
            id: 'abyss',
            name: '虚空裂隙',
            emoji: '🕳️',
            floorDark: [22, 16, 36],
            floorLight: [36, 28, 58],
            floorEdge: [12, 8, 22],
            floorShine: [180, 120, 255, 18],
            borderColor: [8, 4, 16],
            obstacleStyle: 'pillar',
            obstacleCount: 34,
            cornerCount: 3,
            obstacleDark: [40, 28, 70],
            obstacleMid: [80, 55, 130],
            obstacleLight: [160, 120, 220],
            floorMin: 3,
            floorMax: 99,
            weight: 6,
            blurb: '三格宽的裂隙迷宫，嵌着几间小厅，死角埋伏墙弩。幽魂蝠群绕后，法师成对。',
        },
        {
            id: 'necropolis',
            name: '亡灵墓园',
            emoji: '🪦',
            floorDark: [36, 34, 40],
            floorLight: [52, 50, 58],
            floorEdge: [22, 20, 26],
            floorShine: [200, 220, 180, 16],
            borderColor: [14, 12, 16],
            obstacleStyle: 'pillar',
            obstacleCount: 38,
            cornerCount: 4,
            obstacleDark: [48, 46, 52],
            obstacleMid: [90, 88, 96],
            obstacleLight: [140, 138, 150],
            floorMin: 2,
            floorMax: 99,
            weight: 6,
            blurb: '密集墓室格网，门洞相连：一半空棺藏箱子，一半伏兵。骨卫追击，幽灵穿墙。',
        },
        {
            id: 'clockwork',
            name: '齿轮秘库',
            emoji: '⚙️',
            floorDark: [52, 38, 26],
            floorLight: [88, 62, 38],
            floorEdge: [34, 24, 16],
            floorShine: [255, 190, 90, 26],
            borderColor: [22, 14, 10],
            obstacleStyle: 'gear',
            obstacleCount: 38,
            cornerCount: 4,
            obstacleDark: [70, 48, 28],
            obstacleMid: [150, 100, 45],
            obstacleLight: [255, 190, 90],
            floorMin: 3,
            floorMax: 99,
            weight: 5,
            blurb: '黄铜铆钉地板与蒸汽管道：障碍是咬合大齿轮，机油渍发亮。专属机械怪——齿轮滚压、电火花、提线木偶、浮空机甲；与洞穴/沼泽/冰原完全不同。',
        },
    ],
    biomeSpawn: {
        cave: [
            { type: 'tank', weight: 22, hpMul: 1.12, color: [95, 82, 70] },
            { type: 'slime', weight: 22, color: [72, 68, 58] },
            { type: 'beetle', weight: 16, color: [100, 80, 50] },
            { type: 'wolf', weight: 10, floorMin: 2, color: [100, 90, 80] },
            { type: 'spider', weight: 14, floorMin: 2, color: [80, 55, 50] },
            { type: 'shroom', weight: 10, floorMin: 2, color: [140, 90, 70] },
            { type: 'wisp', weight: 8, color: [120, 160, 200] },
            { type: 'fast', weight: 8, color: [110, 98, 82] },
            { type: 'bat', weight: 5, color: [80, 70, 60] },
            { type: 'snake', weight: 5, floorMin: 2, color: [90, 110, 60] },
            { type: 'archer', weight: 4, floorMin: 2, color: [130, 110, 85] },
            { type: 'mage', weight: 3, floorMin: 3, color: [130, 100, 160] },
            { type: 'dragon', weight: 4, floorMin: 3, hpMul: 1.05, color: [190, 80, 45] },
        ],
        ruins: [
            { type: 'archer', weight: 20, color: [190, 185, 200] },
            { type: 'mage', weight: 14, floorMin: 2, color: [170, 140, 210] },
            { type: 'golem', weight: 16, floorMin: 2, hpMul: 1.05, color: [130, 120, 145] },
            { type: 'wolf', weight: 10, floorMin: 2, color: [120, 110, 130] },
            { type: 'tank', weight: 10, hpMul: 1.08, color: [120, 112, 145] },
            { type: 'spider', weight: 10, floorMin: 2, color: [90, 70, 100] },
            { type: 'beetle', weight: 8, color: [110, 100, 130] },
            { type: 'imp', weight: 8, floorMin: 3, color: [160, 80, 120] },
            { type: 'wisp', weight: 6, color: [180, 190, 230] },
            { type: 'moth', weight: 5, color: [180, 150, 200] },
            { type: 'raven', weight: 4, floorMin: 2, color: [60, 55, 80] },
            { type: 'slime', weight: 4, color: [105, 100, 125] },
            { type: 'dragon', weight: 4, floorMin: 3, color: [170, 90, 120] },
        ],
        swamp: [
            { type: 'toad', weight: 18, color: [45, 150, 65] },
            { type: 'crab', weight: 12, color: [180, 70, 50] },
            { type: 'snake', weight: 16, color: [50, 140, 70] },
            { type: 'shroom', weight: 12, color: [160, 80, 70] },
            { type: 'mosquito', weight: 12, color: [55, 130, 45] },
            { type: 'moth', weight: 10, color: [180, 150, 60] },
            { type: 'fast', weight: 10, spdMul: 1.12, color: [55, 170, 85] },
            { type: 'beetle', weight: 8, color: [60, 110, 50] },
            { type: 'wisp', weight: 8, color: [90, 200, 160] },
            { type: 'jelly', weight: 6, floorMin: 2, color: [80, 180, 140] },
            { type: 'archer', weight: 6, floorMin: 2, color: [95, 145, 55] },
            { type: 'slime', weight: 6, color: [48, 125, 72] },
            { type: 'bat', weight: 4, color: [40, 80, 55] },
            { type: 'mage', weight: 2, floorMin: 3, color: [80, 140, 110] },
        ],
        ice: [
            { type: 'crystal', weight: 20, color: [160, 210, 250] },
            { type: 'crab', weight: 10, floorMin: 2, color: [160, 100, 90] },
            { type: 'jelly', weight: 14, color: [140, 210, 240] },
            { type: 'mage', weight: 14, color: [160, 200, 255] },
            { type: 'tank', weight: 12, hpMul: 1.1, spdMul: 0.9, color: [100, 140, 180] },
            { type: 'archer', weight: 10, color: [180, 210, 240] },
            { type: 'wisp', weight: 8, color: [200, 230, 255] },
            { type: 'raven', weight: 8, color: [50, 60, 90] },
            { type: 'spider', weight: 6, floorMin: 3, color: [90, 120, 150] },
            { type: 'bat', weight: 5, color: [100, 120, 160] },
            { type: 'slime', weight: 5, color: [120, 160, 200] },
            { type: 'beetle', weight: 3, color: [90, 120, 150] },
        ],
        sky: [
            { type: 'bat', weight: 18, color: [90, 70, 120] },
            { type: 'jelly', weight: 12, color: [180, 210, 240] },
            { type: 'raven', weight: 10, color: [45, 40, 60] },
            { type: 'moth', weight: 10, color: [220, 190, 120] },
            { type: 'wisp', weight: 14, color: [220, 230, 255] },
            { type: 'fast', weight: 10, color: [180, 200, 240] },
            { type: 'mage', weight: 8, floorMin: 3, color: [170, 150, 220] },
            { type: 'imp', weight: 6, floorMin: 3, color: [200, 100, 140] },
            { type: 'archer', weight: 5, color: [200, 190, 160] },
            { type: 'slime', weight: 3, color: [150, 160, 190] },
            { type: 'dragon', weight: 8, floorMin: 3, hpMul: 1.1, color: [220, 90, 50] },
        ],
        volcano: [
            { type: 'imp', weight: 16, color: [220, 70, 40] },
            { type: 'beetle', weight: 14, color: [120, 60, 40] },
            { type: 'tank', weight: 14, hpMul: 1.1, color: [160, 70, 50] },
            { type: 'dragon', weight: 12, floorMin: 3, hpMul: 1.12, color: [230, 80, 40] },
            { type: 'slime', weight: 10, color: [140, 60, 40] },
            { type: 'mage', weight: 8, color: [200, 90, 70] },
            { type: 'archer', weight: 6, color: [180, 110, 70] },
            { type: 'fast', weight: 6, color: [220, 120, 60] },
            { type: 'bat', weight: 5, color: [90, 40, 35] },
            { type: 'golem', weight: 5, floorMin: 2, color: [130, 70, 55] },
            { type: 'shroom', weight: 4, color: [160, 50, 40] },
            { type: 'crystal', weight: 3, color: [220, 140, 80] },
        ],
        abyss: [
            { type: 'wisp', weight: 16, color: [160, 120, 255] },
            { type: 'jelly', weight: 12, color: [140, 100, 220] },
            { type: 'bat', weight: 12, color: [60, 40, 90] },
            { type: 'imp', weight: 12, color: [140, 50, 160] },
            { type: 'raven', weight: 10, color: [35, 25, 55] },
            { type: 'mage', weight: 10, color: [140, 90, 210] },
            { type: 'spider', weight: 8, color: [70, 40, 90] },
            { type: 'golem', weight: 6, floorMin: 3, color: [90, 70, 130] },
            { type: 'moth', weight: 6, color: [160, 120, 200] },
            { type: 'mosquito', weight: 4, color: [80, 50, 100] },
            { type: 'archer', weight: 4, color: [130, 110, 170] },
            { type: 'dragon', weight: 2, floorMin: 4, color: [120, 40, 160] },
        ],
        necropolis: [
            { type: 'bone', weight: 20, color: [230, 220, 200] },
            { type: 'specter', weight: 16, color: [190, 210, 230] },
            { type: 'shroom', weight: 10, color: [120, 100, 80] },
            { type: 'spider', weight: 10, color: [60, 50, 55] },
            { type: 'wisp', weight: 10, color: [160, 180, 200] },
            { type: 'golem', weight: 8, floorMin: 2, color: [100, 95, 110] },
            { type: 'archer', weight: 8, color: [160, 150, 140] },
            { type: 'mage', weight: 6, floorMin: 2, color: [140, 120, 180] },
            { type: 'raven', weight: 6, color: [40, 38, 50] },
            { type: 'bat', weight: 5, color: [55, 50, 65] },
            { type: 'imp', weight: 4, floorMin: 3, color: [100, 50, 70] },
            { type: 'tank', weight: 3, color: [90, 85, 95] },
            { type: 'slime', weight: 2, color: [80, 90, 70] },
        ],
        clockwork: [
            { type: 'cog', weight: 26, color: [190, 130, 55] },
            { type: 'spark', weight: 22, color: [255, 230, 90] },
            { type: 'puppet', weight: 20, color: [170, 110, 75] },
            { type: 'drone', weight: 18, color: [100, 150, 180] },
            { type: 'cog', weight: 8, floorMin: 4, hpMul: 1.15, color: [220, 150, 60] },
            { type: 'drone', weight: 6, floorMin: 4, color: [80, 160, 200] },
        ],
    },
    encounters: [
        { id: 'scatter_few', placement: 'scatter', slots: [{ source: 'biome', count: 3 }] },
        { id: 'scatter_mid', placement: 'scatter', slots: [{ source: 'biome', count: 5 }] },
        { id: 'scatter_many', placement: 'scatter', slots: [{ source: 'biome', count: 7 }] },
        { id: 'ring_pack', placement: 'ring', slots: [{ source: 'biome', count: 4 }] },
        { id: 'pillar_side', placement: 'pillar', slots: [{ source: 'biome', count: 4 }] },
        { id: 'door_line', placement: 'door', slots: [{ source: 'biome', count: 4 }] },
        {
            id: 'marksmen',
            placement: 'scatter',
            slots: [
                { source: 'enemy', enemyId: 'archer', count: 2 },
                { source: 'biome', count: 2 },
            ],
        },
        {
            id: 'spirit_flock',
            placement: 'ring',
            slots: [
                { source: 'enemy', enemyId: 'wisp', count: 3 },
                { source: 'biome', count: 1 },
            ],
        },
        {
            id: 'raven_pair',
            placement: 'ring',
            slots: [
                { source: 'enemy', enemyId: 'raven', count: 2 },
                { source: 'biome', count: 2 },
            ],
        },
        {
            id: 'arcane_pair',
            placement: 'pillar',
            slots: [
                { source: 'enemy', enemyId: 'mage', count: 2 },
                { source: 'enemy', enemyId: 'wisp', count: 1 },
            ],
        },
        {
            id: 'gear_swarm',
            placement: 'ring',
            slots: [
                { source: 'enemy', enemyId: 'cog', count: 2 },
                { source: 'enemy', enemyId: 'spark', count: 2 },
            ],
        },
        {
            id: 'puppet_line',
            placement: 'door',
            slots: [
                { source: 'enemy', enemyId: 'puppet', count: 2 },
                { source: 'enemy', enemyId: 'drone', count: 1 },
            ],
        },
    ],
    themeEncounters: {
        cave: [
            { encounterId: 'scatter_mid', weight: 8 },
            { encounterId: 'scatter_few', weight: 5 },
            { encounterId: 'ring_pack', weight: 4 },
            { encounterId: 'pillar_side', weight: 3 },
            { encounterId: 'door_line', weight: 4 },
            { encounterId: 'spirit_flock', weight: 3 },
            { encounterId: 'marksmen', weight: 2 },
        ],
        ruins: [
            { encounterId: 'marksmen', weight: 6 },
            { encounterId: 'arcane_pair', weight: 7 },
            { encounterId: 'scatter_mid', weight: 5 },
            { encounterId: 'ring_pack', weight: 3 },
            { encounterId: 'pillar_side', weight: 5 },
            { encounterId: 'spirit_flock', weight: 3 },
            { encounterId: 'scatter_few', weight: 2 },
        ],
        swamp: [
            { encounterId: 'scatter_many', weight: 6 },
            { encounterId: 'spirit_flock', weight: 7 },
            { encounterId: 'scatter_mid', weight: 5 },
            { encounterId: 'marksmen', weight: 4 },
            { encounterId: 'pillar_side', weight: 3 },
            { encounterId: 'arcane_pair', weight: 3 },
            { encounterId: 'door_line', weight: 2 },
        ],
        ice: [
            { encounterId: 'arcane_pair', weight: 7 },
            { encounterId: 'marksmen', weight: 6 },
            { encounterId: 'scatter_mid', weight: 5 },
            { encounterId: 'pillar_side', weight: 5 },
            { encounterId: 'ring_pack', weight: 3 },
            { encounterId: 'spirit_flock', weight: 3 },
            { encounterId: 'raven_pair', weight: 4 },
        ],
        sky: [
            { encounterId: 'spirit_flock', weight: 9 },
            { encounterId: 'raven_pair', weight: 5 },
            { encounterId: 'scatter_mid', weight: 5 },
            { encounterId: 'ring_pack', weight: 5 },
            { encounterId: 'arcane_pair', weight: 4 },
            { encounterId: 'scatter_few', weight: 3 },
            { encounterId: 'marksmen', weight: 2 },
        ],
        volcano: [
            { encounterId: 'ring_pack', weight: 7 },
            { encounterId: 'scatter_mid', weight: 6 },
            { encounterId: 'door_line', weight: 5 },
            { encounterId: 'pillar_side', weight: 4 },
            { encounterId: 'marksmen', weight: 3 },
            { encounterId: 'scatter_many', weight: 3 },
            { encounterId: 'arcane_pair', weight: 2 },
        ],
        abyss: [
            { encounterId: 'spirit_flock', weight: 8 },
            { encounterId: 'raven_pair', weight: 5 },
            { encounterId: 'arcane_pair', weight: 8 },
            { encounterId: 'ring_pack', weight: 5 },
            { encounterId: 'scatter_mid', weight: 4 },
            { encounterId: 'marksmen', weight: 3 },
            { encounterId: 'pillar_side', weight: 3 },
            { encounterId: 'scatter_few', weight: 2 },
        ],
        necropolis: [
            { encounterId: 'spirit_flock', weight: 8 },
            { encounterId: 'raven_pair', weight: 6 },
            { encounterId: 'scatter_mid', weight: 6 },
            { encounterId: 'ring_pack', weight: 5 },
            { encounterId: 'arcane_pair', weight: 4 },
            { encounterId: 'pillar_side', weight: 4 },
            { encounterId: 'marksmen', weight: 3 },
            { encounterId: 'door_line', weight: 2 },
        ],
        clockwork: [
            { encounterId: 'gear_swarm', weight: 9 },
            { encounterId: 'puppet_line', weight: 7 },
            { encounterId: 'ring_pack', weight: 6 },
            { encounterId: 'scatter_mid', weight: 5 },
            { encounterId: 'door_line', weight: 4 },
            { encounterId: 'pillar_side', weight: 3 },
            { encounterId: 'scatter_few', weight: 2 },
        ],
    },
    floors: [
        { floor: 1, enemyCountMul: 0.72, scaleMul: 0.82 },
        { floor: 2, themeId: 'volcano', enemyCountMul: 0.92, scaleMul: 0.95 },
        { floor: 3, themeId: 'necropolis', enemyCountMul: 1.0 },
        { floor: 4, themeId: 'abyss', enemyCountMul: 1.05 },
        { floor: 5, enemyCountMul: 1.12, bossHpMul: 1.06 },
    ],
    dungeon: {
        totalFloors: 5,
        roomsPerFloor: 4,
        roomScaleStep: 0.18,
        bossHpBase: 340,
        bossHpPerFloor: 110,
        bossSpeedBase: 52,
        bossSpeedPerFloor: 4,
        bossDamageBase: 28,
        bossDamagePerFloor: 5,
        bossAttackRange: 95,
        bossBehaviorId: 'boss',
        finalBossHpBase: 680,
        finalBossHpPerFloor: 50,
        finalBossSpeed: 70,
        finalBossDamage: 36,
        finalBossAttackRange: 110,
        finalRoomTrashCap: 3,
        summonCount: 3,
        summonHp: 32,
        summonSpeed: 95,
        summonDamage: 10,
        summonAttackRange: 50,
        summonDetectionRange: 700,
    },
    items: [
        { id: 'potion_hp', name: '治疗药水', emoji: '🧪', desc: '立刻回复生命。', kind: 'heal', amount: 42, rarity: 'common', dropWeight: 14 },
        { id: 'potion_rage', name: '狂暴药剂', emoji: '🍶', desc: '短时间提高攻击。', kind: 'buff', amount: 8, rarity: 'rare', dropWeight: 5 },
        { id: 'scroll_haste', name: '疾风卷轴', emoji: '📜', desc: '短时间提高移速。', kind: 'buff', amount: 40, rarity: 'rare', dropWeight: 5 },
        { id: 'bomb', name: '爆裂弹', emoji: '💣', desc: '投向面前，炸开一小圈。', kind: 'throw', amount: 64, rarity: 'common', dropWeight: 8 },
        { id: 'amulet', name: '岩护符', emoji: '📿', desc: '提高这一局的防御。', kind: 'buff', amount: 2, rarity: 'epic', dropWeight: 2 },
        { id: 'compass', name: '地牢罗盘', emoji: '🧭', desc: '标出当前层传送门方向。', kind: 'buff', amount: 1, rarity: 'rare', dropWeight: 3 },
        { id: 'potion_shield', name: '护盾药水', emoji: '🛡', desc: '获得护盾，先于生命吸收伤害。', kind: 'buff', amount: 30, rarity: 'rare', dropWeight: 6 },
        { id: 'scroll_magnet', name: '磁引卷轴', emoji: '🧲', desc: '数秒内全场掉落飞向你。', kind: 'buff', amount: 5, rarity: 'rare', dropWeight: 4 },
        { id: 'frost_bomb', name: '冰霜弹', emoji: '❄', desc: '投向面前，炸开并大幅减速敌人。', kind: 'throw', amount: 48, rarity: 'rare', dropWeight: 6 },
        { id: 'elixir_life', name: '生命精华', emoji: '💛', desc: '本局生命上限永久提高并回血。', kind: 'buff', amount: 15, rarity: 'epic', dropWeight: 2 },
        { id: 'scroll_crit', name: '锐目卷轴', emoji: '🎯', desc: '短时间大幅提高暴击率。', kind: 'buff', amount: 25, rarity: 'rare', dropWeight: 4 },
        { id: 'coin_pouch', name: '鼓鼓钱袋', emoji: '💰', desc: '打开即得一把金币。', kind: 'buff', amount: 12, rarity: 'common', dropWeight: 7 },
    ],
    talents: [
        {
            id: 'hp_up', name: '坚韧', emoji: '❤', desc: '生命 +18/级',
            maxLevel: 5, costBase: 3, costStep: 2, requires: [],
            effects: [{ kind: 'stat', stat: 'maxHp', perLevel: 18 }],
        },
        {
            id: 'atk_up', name: '锋刃', emoji: '⚔', desc: '攻击 +9/级',
            maxLevel: 5, costBase: 4, costStep: 2, requires: [],
            effects: [{ kind: 'stat', stat: 'atk', perLevel: 9 }],
        },
        {
            id: 'spd_up', name: '疾步', emoji: '💨', desc: '移速 +28/级',
            maxLevel: 5, costBase: 3, costStep: 2, requires: [],
            effects: [{ kind: 'stat', stat: 'moveSpeed', perLevel: 28 }],
        },
        {
            id: 'def_up', name: '护甲', emoji: '🛡', desc: '防御 +4/级',
            maxLevel: 5, costBase: 4, costStep: 2, requires: ['hp_up'],
            effects: [{ kind: 'stat', stat: 'def', perLevel: 4 }],
        },
        {
            id: 'crit_up', name: '暴击', emoji: '💥', desc: '暴击率 +5%/级',
            maxLevel: 5, costBase: 5, costStep: 3, requires: ['atk_up'],
            effects: [{ kind: 'stat', stat: 'critChance', perLevel: 0.05 }],
        },
        {
            id: 'crit_dmg', name: '致命', emoji: '☠', desc: '暴击倍率 +0.25/级',
            maxLevel: 3, costBase: 6, costStep: 4, requires: ['crit_up'],
            effects: [{ kind: 'stat', stat: 'critMultiplier', perLevel: 0.25 }],
        },
        {
            id: 'kill_heal', name: '嗜血', emoji: '🩸', desc: '击杀回血 +5/级',
            maxLevel: 3, costBase: 5, costStep: 3, requires: ['hp_up', 'atk_up'],
            effects: [{ kind: 'kill_heal', perLevel: 5 }],
        },
        {
            id: 'balanced', name: '均衡', emoji: '⚖', desc: '生命+12 攻击+4 防御+2 /级',
            maxLevel: 3, costBase: 6, costStep: 3, requires: ['def_up', 'spd_up'],
            effects: [
                { kind: 'stat', stat: 'maxHp', perLevel: 12 },
                { kind: 'stat', stat: 'atk', perLevel: 4 },
                { kind: 'stat', stat: 'def', perLevel: 2 },
            ],
        },
        {
            id: 'quick_skill', name: '迅技', emoji: '⏱', desc: '技能冷却 -12%/级',
            maxLevel: 3, costBase: 5, costStep: 3, requires: ['spd_up'],
            effects: [{ kind: 'skill_cd', perLevel: 0.12 }],
        },
        {
            id: 'magnet_field', name: '磁场', emoji: '🧲', desc: '拾取范围 +70/级',
            maxLevel: 3, costBase: 3, costStep: 2, requires: [],
            effects: [{ kind: 'pickup_range', perLevel: 70 }],
        },
    ],
    drops: [
        {
            id: 'trash',
            coinChance: 0.72,
            coinMin: 2,
            coinMax: 6,
            heartChance: 0.18,
            heartAmount: 18,
            lootKind: 'coin',
            itemChance: 0.24,
            itemPool: ['potion_hp', 'scroll_haste', 'bomb', 'potion_rage', 'potion_shield', 'frost_bomb', 'coin_pouch', 'scroll_crit', 'scroll_magnet'],
        },
        {
            id: 'elite',
            coinChance: 1,
            coinMin: 6,
            coinMax: 10,
            heartChance: 0.5,
            heartAmount: 20,
            lootKind: 'coin',
            itemChance: 0.8,
            itemPool: ['potion_hp', 'potion_shield', 'frost_bomb', 'scroll_crit', 'coin_pouch', 'scroll_magnet'],
        },
        {
            id: 'boss',
            coinChance: 1,
            coinMin: 14,
            coinMax: 24,
            heartChance: 1,
            heartAmount: 45,
            lootKind: 'chest',
            itemChance: 0.95,
            itemPool: ['potion_hp', 'potion_rage', 'bomb', 'amulet', 'compass', 'elixir_life', 'potion_shield', 'scroll_magnet'],
        },
    ],
    shop: [
                                                                                {
            id: 'unlock_ranger', kind: 'character', characterId: 'ranger',
            name: '解锁游侠', desc: '永久解锁游侠（大厅可选出战）', cost: 12,
        },
        {
            id: 'unlock_mage', kind: 'character', characterId: 'mage',
            name: '解锁法师', desc: '永久解锁法师（大厅可选出战）', cost: 18,
        },
        {
            id: 'unlock_paladin', kind: 'character', characterId: 'paladin',
            name: '解锁圣骑士', desc: '高级角色 · 开局圣光巨刃 + 壁垒技能', cost: 48,
        },
        {
            id: 'unlock_assassin', kind: 'character', characterId: 'assassin',
            name: '解锁影刃', desc: '高级角色 · 开局影舞双匕 + 闪击技能', cost: 55,
        },
        {
            id: 'unlock_dragonkin', kind: 'character', characterId: 'dragonkin',
            name: '解锁龙裔', desc: '高级角色 · 开局龙牙戟 + 龙息技能', cost: 68,
        },
        {
            id: 'unlock_berserker', kind: 'character', characterId: 'berserker',
            name: '解锁狂战', desc: '高级角色 · 开局血劈巨斧 + 狂战技能', cost: 52,
        },
        {
            id: 'unlock_geomancer', kind: 'character', characterId: 'geomancer',
            name: '解锁地脉师', desc: '高级角色 · 开局岩晶杖 + 地脉技能', cost: 58,
        },
        {
            id: 'unlock_stormcaller', kind: 'character', characterId: 'stormcaller',
            name: '解锁唤雷', desc: '高级角色 · 开局唤雷杖 + 雷击技能', cost: 62,
        },
        {
            id: 'unlock_cryomancer', kind: 'character', characterId: 'cryomancer',
            name: '解锁霜语', desc: '高级角色 · 开局冰晶球 + 霜技能', cost: 60,
        },
        {
            id: 'unlock_warden', kind: 'character', characterId: 'warden',
            name: '解锁戟卫', desc: '高级角色 · 开局守望戟 + 结界技能', cost: 54,
        },
        {
            id: 'unlock_plague', kind: 'character', characterId: 'plague',
            name: '解锁疫医', desc: '高级角色 · 开局毒瓶 + 疫雾技能', cost: 56,
        },
        {
            id: 'unlock_voidwalker', kind: 'character', characterId: 'voidwalker',
            name: '解锁虚空行者', desc: '高级角色 · 开局虚空刃 + 裂隙技能', cost: 72,
        },
        {
            id: 'unlock_sunpriest', kind: 'character', characterId: 'sunpriest',
            name: '解锁日曜祭司', desc: '高级角色 · 开局日轮杖 + 圣焰技能', cost: 70,
        },
                                                                                                        {
            id: 'perm_max_hp', kind: 'perm_stat', purchaseKey: 'maxHp', amount: 10,
            name: '永久生命', desc: '开局更耐揍（可叠加）', cost: 25, stackable: true,
        },
        {
            id: 'perm_atk', kind: 'perm_stat', purchaseKey: 'atk', amount: 2,
            name: '永久锋刃', desc: '开局刀更锋（可叠加）', cost: 28, stackable: true,
        },
        {
            id: 'perm_def', kind: 'perm_stat', purchaseKey: 'def', amount: 1,
            name: '永久护甲', desc: '开局更扛打（可叠加）', cost: 22, stackable: true,
        },
        {
            id: 'perm_speed', kind: 'perm_stat', purchaseKey: 'moveSpeed', amount: 8,
            name: '永久疾风', desc: '开局脚下生风（可叠加）', cost: 24, stackable: true,
        },
        {
            id: 'kit_heal', kind: 'kit', itemId: 'potion_hp', amount: 1,
            name: '补给·治疗药水', desc: '存入补给箱，开战自动装进背包', cost: 6,
        },
        {
            id: 'kit_rage', kind: 'kit', itemId: 'potion_rage', amount: 1,
            name: '补给·狂暴药剂', desc: '存入补给箱，开战自动装进背包', cost: 8,
        },
        {
            id: 'kit_bomb', kind: 'kit', itemId: 'bomb', amount: 1,
            name: '补给·爆裂弹', desc: '存入补给箱，开战自动装进背包', cost: 7,
        },
        {
            id: 'kit_haste', kind: 'kit', itemId: 'scroll_haste', amount: 1,
            name: '补给·疾风卷轴', desc: '存入补给箱，开战自动装进背包', cost: 5,
        },
    ],
    stages: [
        {
            id: 's1_cave', name: '幽暗试炼', emoji: '🪨',
            desc: '入门关。单层洞穴，熟悉移攻与清房。',
            totalFloors: 1, clearBonusSoul: 8,
            themeId: 'cave', scaleMul: 0.9,
        },
        {
            id: 's2_swamp', name: '毒沼浅滩', emoji: '🌿',
            desc: '泥洼减速。学会绕开热点再战。',
            totalFloors: 1, clearBonusSoul: 10,
            unlockAfter: 's1_cave', themeId: 'swamp', scaleMul: 0.95,
            rewardItemId: 'potion_hp', rewardItemAmount: 1,
        },
        {
            id: 's3_ruins', name: '遗迹双塔', emoji: '🏛️',
            desc: '两层遗迹。圣坛加速可穿插走位。',
            totalFloors: 2, clearBonusSoul: 16,
            unlockAfter: 's2_swamp', themeId: 'ruins',
        },
        {
            id: 's4_volcano', name: '熔岩关口', emoji: '🌋',
            desc: '两层火口。熔浆带减速，火龙更活跃。',
            totalFloors: 2, clearBonusSoul: 20,
            unlockAfter: 's3_ruins', themeId: 'volcano', scaleMul: 1.05,
            rewardItemId: 'bomb', rewardItemAmount: 1,
        },
        {
            id: 's5_frost', name: '冰云连关', emoji: '🧊',
            desc: '两层。先冰原再云海（层覆盖随机主题时仍偏难）。',
            totalFloors: 2, clearBonusSoul: 24,
            unlockAfter: 's4_volcano', themeId: 'ice', scaleMul: 1.08,
            rewardItemId: 'potion_rage', rewardItemAmount: 1,
        },
        {
            id: 's6_abyss', name: '虚空终章', emoji: '🕳️',
            desc: '三层裂隙。引力环拉扯，通关战役。',
            totalFloors: 3, clearBonusSoul: 40,
            unlockAfter: 's5_frost', themeId: 'abyss', scaleMul: 1.12,
            rewardItemId: 'scroll_haste', rewardItemAmount: 1,
        },
        {
            id: 's7_grave', name: '墓园余烬', emoji: '🪦',
            desc: '两层亡灵。骨卫与幽灵飞落，通关记星。',
            totalFloors: 2, clearBonusSoul: 48,
            unlockAfter: 's6_abyss', themeId: 'necropolis', scaleMul: 1.18,
            rewardItemId: 'amulet', rewardItemAmount: 1,
        },
    ],
    economy: {
        coinDropChance: 0.62,
        coinValueMin: 2,
        coinValueMax: 5,
        shopItemCount: 4,
        deathSoulPerFloor: 1.5,
        deathSoulPerKills: 8,
        deathSoulPerCoins: 30,
        deathSoulCap: 48,
        floorClearSoulBase: 3,
        floorClearSoulPerFloor: 1,
        clearBonusSoul: 24,
    },
};
